[project]
name = "binder-ex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Steffen Desktop", email = "steffen.clausen@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "notebook>=7.6.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
binder-ex = "binder_ex:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
